# Generated by Django 5.2 on 2025-05-10 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('beneficiaryId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contactNumber', models.CharField(max_length=20)),
                ('relationshipToInsured', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'beneficiary',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policyId', models.AutoField(primary_key=True, serialize=False)),
                ('policyType', models.CharField(max_length=100)),
                ('premiumAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
            options={
                'db_table': 'policy',
            },
        ),
        migrations.CreateModel(
            name='PolicyHolder',
            fields=[
                ('id_number', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'policyholder',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('claimId', models.AutoField(primary_key=True, serialize=False)),
                ('dateFiled', models.DateField(auto_now_add=True)),
                ('claimAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('beneficiaryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.beneficiary')),
                ('policyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.policy')),
                ('policyHolderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.policyholder')),
            ],
            options={
                'db_table': 'claim',
            },
        ),
        migrations.CreateModel(
            name='InsuredPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('relationship_to_policy_holder', models.CharField(max_length=100)),
                ('policy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.policy')),
            ],
            options={
                'db_table': 'insuredperson',
            },
        ),
        migrations.CreateModel(
            name='FraudPreventionTeam',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('contactNumber', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('investigatorName', models.CharField(max_length=255)),
                ('claimid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.claim')),
                ('policyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.policy')),
            ],
            options={
                'db_table': 'fraudpreventionteam',
            },
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.policy'),
        ),
        migrations.AddField(
            model_name='policy',
            name='policyHolder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.policyholder'),
        ),
    ]
