# Generated by Django 5.2 on 2025-04-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFPWebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('claimId', models.AutoField(primary_key=True, serialize=False)),
                ('policyId', models.IntegerField()),
                ('beneficiaryId', models.IntegerField()),
                ('policyHolderId', models.IntegerField()),
                ('dateFiled', models.DateField(auto_now_add=True)),
                ('claimAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
    ]
