# Generated by Django 5.2 on 2025-05-11 15:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFPWebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.IntegerField()),
                ('requires_manual_approval', models.BooleanField(default=False)),
                ('assessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('policyHolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.policyholder')),
            ],
            options={
                'db_table': 'risk_assessment',
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('policyHolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.policyholder')),
            ],
            options={
                'db_table': 'suspicious_activity',
            },
        ),
    ]
