# Generated by Django 5.2 on 2025-04-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFPWebApp', '0002_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuredPerson',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('policy_id', models.BigIntegerField()),
                ('date_of_birth', models.CharField(max_length=100)),
                ('consent_verified', models.IntegerField()),
                ('relationship_to_policy_holder', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ifps_app_insuredperson',
            },
        ),
    ]
