# Generated by Django 5.2 on 2025-04-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IFPWebApp', '0005_teammember'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='policyholder',
            table='ifps_app_policyholder',
        ),
    ]
