# Generated by Django 5.2 on 2025-04-09 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFPWebApp', '0006_alter_policyholder_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudPreventionTeam',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('contactNumber', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('investigatorName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fraudpreventionteam',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policyId', models.AutoField(primary_key=True, serialize=False)),
                ('policyType', models.CharField(max_length=100)),
                ('premiumAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
            options={
                'db_table': 'policy',
            },
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.RemoveField(
            model_name='insuredperson',
            name='consent_verified',
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='relationshipToInsured',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='claim',
            name='beneficiaryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.beneficiary'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='policyHolderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.policyholder'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='relationship_to_policy_holder',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='policyHolderId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='beneficiary',
            table='beneficiary',
        ),
        migrations.AlterModelTable(
            name='claim',
            table='claim',
        ),
        migrations.AlterModelTable(
            name='insuredperson',
            table='insuredperson',
        ),
        migrations.AlterModelTable(
            name='policyholder',
            table='policyholder',
        ),
        migrations.AddField(
            model_name='fraudpreventionteam',
            name='claimid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.claim'),
        ),
        migrations.AddField(
            model_name='policy',
            name='policyHolder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.policyholder'),
        ),
        migrations.AddField(
            model_name='fraudpreventionteam',
            name='policyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.policy'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.policy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='policyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.policy'),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='policy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.policy'),
        ),
    ]
