# Generated by Django 5.2 on 2025-05-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFPWebApp', '0007_fraudpreventionteam_policy_delete_teammember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
