# Generated by Django 5.1.7 on 2025-06-07 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyHolder',
            fields=[
                ('id_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('name', models.CharField(max_length=200)),
                ('beneficiary_changes', models.IntegerField(default=0)),
                ('claims_last_year', models.IntegerField(default=0)),
                ('incomplete_documents', models.BooleanField(default=False)),
                ('activity_timeline', models.JSONField(default=list)),
                ('risk_score', models.FloatField(default=0.0)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policyholder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'policyholder',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policyId', models.AutoField(primary_key=True, serialize=False)),
                ('policyType', models.CharField(max_length=50)),
                ('premiumAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('policyHolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policyapp.policyholder')),
            ],
            options={
                'db_table': 'policy',
            },
        ),
    ]
