# Generated by Django 5.1.7 on 2025-06-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyholder',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
