# Generated by Django 5.2 on 2025-04-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('beneficiaryId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(max_length=10)),
                ('relationshipToInsured', models.CharField(max_length=50)),
            ],
        ),
    ]
