# Generated by Django 5.1.6 on 2025-05-13 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(max_length=50)),
                ('relationshipToInsured', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policyID', models.AutoField(primary_key=True, serialize=False)),
                ('policyType', models.CharField(max_length=100)),
                ('premiumAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PolicyHolder',
            fields=[
                ('idno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsuredPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('relationshipToPolicyHolder', models.CharField(max_length=50)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.policy')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.beneficiary')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.policy')),
            ],
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.policy'),
        ),
        migrations.AddField(
            model_name='policy',
            name='policyHolder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.policyholder'),
        ),
    ]
