# Generated by Django 5.2 on 2025-04-08 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='amount',
            new_name='claimAmount',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='claim_id',
            new_name='claimId',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='beneficiary_id',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='reason',
        ),
        migrations.AddField(
            model_name='claim',
            name='beneficiaryId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='dateFiled',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 4, 8)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='policyHolderId',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='policyId',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
