# Generated by Django 5.2.1 on 2025-06-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressId', models.AutoField(primary_key=True, serialize=False)),
                ('streetAddress', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postalCode', models.CharField(max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('idNumber', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('homeLanguage', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'citizen',
                'managed': False,
            },
        ),
    ]
