# Generated by Django 5.2 on 2025-05-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IFPWebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='email',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='policyholder',
            old_name='email',
            new_name='username',
        ),
    ]
