# Generated by Django 5.2.1 on 2025-06-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFPWebApp', '0002_activitylog_beneficiary_insuredperson_marriage_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuredperson',
            name='status',
            field=models.CharField(choices=[('alive', 'Alive'), ('deceased', 'Deceased')], default='alive', max_length=10),
        ),
    ]
