# Generated by Django 5.2 on 2025-05-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IFPWebApp', '0002_rename_email_admin_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='username',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='policyholder',
            old_name='username',
            new_name='email',
        ),
    ]
