# Generated by Django 5.2 on 2025-05-13 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFPWebApp', '0002_riskassessment_suspiciousactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('officerID', models.AutoField(primary_key=True, serialize=False)),
                ('contactNumber', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=50)),
                ('officerName', models.CharField(max_length=100)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.claim')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('caseID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.officer')),
            ],
        ),
    ]
