# Generated by Django 5.2.3 on 2025-06-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFPWebApp', '0002_activitylog_beneficiary_faceencoding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyholder',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
