# Generated by Django 5.2 on 2025-05-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFPWebApp', '0003_rename_username_admin_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyholder',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
    ]
