# Generated by Django 5.2 on 2025-05-13 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IFPWebApp', '0003_officer_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='startDate',
            new_name='start_date',
        ),
    ]
