# Generated by Django 5.2 on 2025-05-13 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFPWebApp', '0004_rename_startdate_policy_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=10)),
                ('policy_holder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.policyholder')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.riskreport')),
            ],
        ),
        migrations.CreateModel(
            name='SuspiciousPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_description', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.riskreport')),
            ],
        ),
    ]
