# Generated by Django 5.2 on 2025-05-13 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFPWebApp', '0005_riskreport_activitylog_suspiciouspattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuredperson',
            name='holder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IFPWebApp.policyholder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policyholder',
            name='activity_timeline',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='beneficiary_changes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='claims_last_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='incomplete_documents',
            field=models.BooleanField(default=False),
        ),
    ]
