# Generated by Django 5.1.6 on 2025-05-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFPWebApp', '0005_alter_admin_id_alter_admin_table_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
            options={
                'db_table': 'activity_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
