# Generated by Django 5.2 on 2025-05-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IFPWebApp', '0006_insuredperson_holder_policyholder_activity_timeline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskassessment',
            name='policyHolder',
        ),
        migrations.RemoveField(
            model_name='riskreport',
            name='policy_holder',
        ),
        migrations.RemoveField(
            model_name='suspiciouspattern',
            name='report',
        ),
        migrations.RemoveField(
            model_name='suspiciousactivity',
            name='policyHolder',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='RiskAssessment',
        ),
        migrations.DeleteModel(
            name='RiskReport',
        ),
        migrations.DeleteModel(
            name='SuspiciousPattern',
        ),
        migrations.DeleteModel(
            name='SuspiciousActivity',
        ),
    ]
